# Generated by Django 2.2.5 on 2019-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchs',
            name='id',
        ),
        migrations.AlterField(
            model_name='branchs',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
