# Generated by Django 2.2.5 on 2019-09-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_d', '0002_auto_20190915_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branchs',
            new_name='Branches',
        ),
    ]
