# Generated by Django 2.2.5 on 2019-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_d', '0003_auto_20190915_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.CharField(max_length=80),
        ),
    ]
